
import { Image, Download, Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import MagicalImageSkeleton from "@/components/MagicalImageSkeleton";

interface GeneratedImageDisplayProps {
  isGenerating: boolean;
  generationPhase: 'connecting' | 'generating' | 'finalizing';
  generatedImageUrl: string | null;
  selectedImagesCount: number;
  onDownload: () => void;
  onReset: () => void;
}

export const GeneratedImageDisplay = ({
  isGenerating,
  generationPhase,
  generatedImageUrl,
  selectedImagesCount,
  onDownload,
  onReset,
}: GeneratedImageDisplayProps) => {
  return (
    <Card className="cute-border cute-shadow">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-mim-teal">
          <Image className="w-5 h-5" />
          Generated Image
        </CardTitle>
      </CardHeader>
      <CardContent>
        {isGenerating ? (
          <MagicalImageSkeleton phase={generationPhase} />
        ) : generatedImageUrl ? (
          <div className="space-y-4">
            <img
              src={generatedImageUrl}
              alt="Generated by JORBO AI"
              className="w-full rounded-lg border border-mim-teal/30 shadow-lg dark:border-mim-teal-light/30"
            />
            <div className="flex gap-2">
              <Button 
                onClick={onDownload}
                variant="outline" 
                className="flex-1 border-mim-teal text-mim-teal hover:bg-mim-teal hover:text-white dark:border-mim-teal-light dark:text-mim-teal-light dark:hover:bg-mim-teal-light dark:hover:text-gray-900"
              >
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
              <Button 
                onClick={onReset}
                variant="outline"
                className="px-4"
              >
                New
              </Button>
            </div>
          </div>
        ) : (
          <div className="h-64 border-2 border-dashed border-mim-teal/30 rounded-lg flex items-center justify-center dark:border-mim-teal-light/30">
            <div className="text-center text-muted-foreground">
              <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-50" />
              <p className="font-medium">Your AI masterpiece will appear here</p>
              <p className="text-sm mt-1">
                {selectedImagesCount > 0 
                  ? "🎨 Image-to-image editing mode" 
                  : "✨ Text-to-image generation mode"}
              </p>
              <p className="text-xs mt-2 opacity-75">
                Powered by JORBO AI Engine
              </p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
