// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxzmcghgauqnozyjkbzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4em1jZ2hnYXVxbm96eWprYnp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTAwMjAsImV4cCI6MjA2NTA2NjAyMH0.sqZ2hj2XGo5bo7PJO3RBCr6UNK7Bf6cAVmsxsB1vxpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);